language: go
go:
  - 1.12.x
env:
  - GO111MODULE=on
install:
  - make setup-ci
script:
  - make lint-ci
  - make check
  #- make coverage-ci
before_deploy:
  - npx semantic-release
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --config=config/.goreleaser.yml
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
