fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-build
      - id: golangci-lint
        stages: [push]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: forbid-binary
      - id: go-mod-tidy
      - id: go-test
        stages: [push]
