fail_fast: false
default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v1.0.0
    hooks:
      - id: commitlint
        args: ['--config=config/commitlint.config.js']
        additional_dependencies: ['@commitlint/config-conventional']
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: check
        name: make check
        language: system
        types: [go]
        entry: make check
        stages: [push]
      - id: lint
        name: make lint
        language: system
        types: [go]
        entry: make lint
        stages: [push]
