linters-settings:
  dupl:
    threshold: 150
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
  disable-all: false
  fast: false
