builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  main: ./cmd/standup-reporter/main.go
archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - none*
  wrap_in_directory: false
  replacements:
    darwin: macOS
    amd64: x86_64
